### ISSUE TITLE
Program running issue

### ISSUE THREAD

**Issue by yizhiheng** [GeorgeA93/ImageCompression#1]
Hi GeorgeA93,

I cloned your project and imported to my IDE. But when I tried to run the program, it said "Exception in thread "main" java.lang.UnsatisfiedLinkError: no opencv_java2410 in java.library.path". Just like the img below.
<img width="1393" alt="screen shot 2015-10-04 at 11 47 50 am" src="https://cloud.githubusercontent.com/assets/3829080/10268669/c5a5356c-6a8d-11e5-8611-5667076ec8c5.png">
Any idea to solve this? Is this the opencv jar problem? Do I need to rebuild the jar or something?

Thank you very much!

**Comment by GeorgeA93** [comment]
Good evening.

I do not think rebuilding the opencv jar will solve the problem. It has been a long time since I looked at this project, however I think you may need to re set up the dependencies. I would have a look around on google for resources on how to set up opencv in IntelliJ. This may involve re downloading the latest opencv files and linking them in the appropriate manner.

This link may help? http://labusers.net/member/YoshitomoMatsubara/menu/blog.php?path=20150516.html

Sorry for the limited reply, but you should note that i set up this project in eclipse as I could not get it to function as expected in my copy of IntelliJ at the time.

Many thanks

George
